version: "3.7"

services:
    website:
        build:
            context: .
            dockerfile: Dockerfile
        image: trovster_mymove:latest
        container_name: trovster_mymove
        ports:
            - '${FORWARD_APP_PORT:-80}:80'
        volumes:
            - ./:/var/www/html
        networks:
            - trovster_mymove

    mysql:
        image: 'mysql:5.7'
        platform: linux/x86_64
        container_name: trovster_mymove_mysql
        ports:
            - '${FORWARD_DB_PORT:-3306}:3306'
        env_file:
            - ./.env
        environment:
            MYSQL_DATABASE: '${DB_DATABASE}'
            MYSQL_USER: '${DB_USER}'
            MYSQL_PASSWORD: 'password'
            MYSQL_ROOT_PASSWORD: ''
            MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
        command:
            - --default-authentication-plugin=mysql_native_password
            - --sql_mode=
        volumes:
            - ./.db:/var/lib/mysql
            - ./database.sql:/docker-entrypoint-initdb.d/init.sql
        healthcheck:
            test: ["CMD", "mysqladmin", "ping"]
        restart: 'unless-stopped'
        networks:
            - trovster_mymove

networks:
    trovster_mymove:
        driver: bridge
